### ISSUE TITLE
cd <tab> shows error messages

### ISSUE THREAD

**Issue by PlasmaHH** [mgalgs/fuzzy_bash_completion#12]
In plain bash, doing cd <tab> (or any other command) displays all files or asks to display (if they are too many) however with fuzzy bc there are a couple of errors emitted beforehand:

```
Try 'dirname --help' for more information.
basename: missing operand
Try 'basename --help' for more information.

```

**Comment by mgalgs** [comment]
Thanks for the report, should be fixed :+1:

**Comment by PlasmaHH** [comment]
Indeed, no erros anymore
