### ISSUE TITLE
Getting error: _get_comp_words_by_ref: command not found

### ISSUE THREAD

**Issue by maep--** [mgalgs/fuzzy_bash_completion#14]
Following the setup instructions, I got this error when pressing tab:
_get_comp_words_by_ref: command not found

I managed to fix it by putting `source /etc/profile.d/bash_completion.sh` before sourcing fuzzy_bash_completion. I'm running Debian 9.8. Maybe you could  put a note about that in the readme.

**Comment by mgalgs** [comment]
The README did already mention `bash-completion` as a pre-requisite.  I've added another sentence that should make it clear that you not only have to install it but also _enable_ it as well.  LMK what you think.

**Comment by maep--** [comment]
Thanks. To elaborate, I wasn't aware that bash-completion needed to be explicitly activated. I thought simply having it installed was enough.

**Comment by mgalgs** [comment]
Yeah that's a pretty common misunderstanding with the `bash-completion` package... To make matters worse, some distros _do_ automatically search for it in their system-wide rc scripts and enable it if it's installed.  Sounds like Debian 9.8 doesn't do that.  We can't really describe how to install and enable it on each and every distro so hopefully that subtle additional note in the README will be enough to get people unstuck...

Thanks for the report and feedback.
