### ISSUE TITLE
Error `bash: declare: -A: invalid option` 

### ISSUE THREAD

**Issue by xbao** [mgalgs/fuzzy_bash_completion#8]
When I try and source `fuzzy_bash_completion`:

```
source ../fuzzy_bash_completion/fuzzy_bash_completion 
bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

I'm using Mac OSX Yosemite, bash 3.2.

**Comment by mgalgs** [comment]
Thanks for the report.  Unfortunately you need `bash >= 4`.  See [this](https://github.com/mgalgs/fuzzy_bash_completion/blob/master/fuzzy_bash_completion#L5) comment in the code (I should really print a warning)...  You can [install it with `brew`](http://superuser.com/questions/857250/how-to-update-bash-on-mac-os-x-yosemite).

**Comment by xbao** [comment]
Oh cool, thanks! Maybe a line in the README might be an idea?

**Comment by mgalgs** [comment]
Done, thanks!
