### ISSUE TITLE
Requires bash-completion

### ISSUE THREAD

**Issue by Lenbok** [mgalgs/fuzzy_bash_completion#9]
If bash-completion is not installed, then _get_comp_words_by_ref is not available, and fuzzy_bash_completion produces a bunch of error messages when you try to use it.

At the least, it would be good to list this in the requirements.

**Comment by mgalgs** [comment]
Ah, didn't know `_get_comp_words_by_ref` was from `bash-completion`.  I had made a note about optionally needing the `bash-completion` package [here](https://github.com/mgalgs/fuzzy_bash_completion#fuzzy_replace_filedir_xspec-not-working) but looks like it's not optional after all.
